version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: worker-queue
    ports:
      - 6379:6379

  adminer:
    image: apache/kafka:latest
    container_name: broker
    ports:
      - 9092:9092
